name: rpa

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

                - name: Docker Build & Push Action

    - name: Publicando no docker
      uses: mr-smithers-excellent/docker-build-push@v6.4
      with:
        # Name of the Docker image
        image: lucalucareli/rpa
        tags: 1,lasted
        registry: docker.io
        dockerfile: dockerfile
        username: ${{secrets.dockeruser}}
        password: ${{secrets.dockerpassword}}
